server:
  port: 8040
opentracing: 
  jaeger:
    udp-sender:
      host: ${JAEGER_HOST}  ## localhost
      port: ${JAEGER_PORT}   ## 6831
spring:
  application:
    name: users
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQLDB_URL}
    username: ${MYSQLDB_USERNAME}
    password: ${MYSQLDB_PASSWORD}
  jpa:
    hibernate.ddl-auto: update  
    show-sql: true
    properties: 
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect